sudo: required
services:
  - docker
before_install:
  - wget https://github.com/rf-/roadshow/releases/download/v1.0.0/roadshow-linux64
script:
  - ./roadshow-linux64 run
notifications:
  email: false
